### ISSUE TITLE
Barriors (or lack thereof) in dm1

### ISSUE THREAD

**Issue by Danfun64** [Turtle-Arena/turtle-arena-data#3]
In dm1, it is possible to get to the very top of the map by using a sword in a specific way. It is a little difficult to do and has no benefit, but I wanted to let you know about it and whether you think it is worth fixing, not fixing, or even encouraging use of...

http://www.mediafire.com/download/jjfqr99clrxpvcj/goingup3.mintdemo

**Comment by zturtleman** [comment]
I knew it was possible using the bamboo and maybe bo weapons, but not swords. I'm thinking about what to do with it and a few other minor improvements to the map.

**Comment by zturtleman** [comment]
Added a ladder (which bots don't use yet...) and few items up there in 9340e747c113a7f9186a4ab9f7a2e57208fe3908.
